test = {   'name': 'q6a',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> zero_predictor_fp >= 0\n'
                                               'True',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> zero_predictor_fn >= 0\n'
                                               'True',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> zero_predictor_fp\n0',
                                       'hidden': True,
                                       'locked': False},
                                   {   'code': '>>> zero_predictor_fn\n1918',
                                       'hidden': True,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
